### ISSUE TITLE
planetcyborg-dns-reload nicht im Repo

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ffhb-dns#2]
`planetcyborg-dns-reload` aus https://github.com/FreifunkBremen/ffhb-dns/blob/master/update-dns.sh wird für ansible benötigt

**Comment by ghost** [comment]
Nein. Wird es nicht.

**Comment by ghost** [comment]
Die Zone wird nicht auf den VPN-Servern gebaut, sondern nur fuer die DNS-Server (Die stehen extra.). Mir ist nicht bekannt, dass das geaendert werden soll.

**Comment by genofire** [comment]
warum nicht die vpns als dns-server für die Zonr benutzen?

**Comment by ghost** [comment]
Weil das bisher nicht so ist. Das muesste mMn diskutiert werden. vpn01 stuende dafuer nicht zur Verfuegung. vpn04 weiss ich nicht, etc. pp.

**Comment by ghost** [comment]
Und vor allem: Why change running system?

**Comment by genofire** [comment]
"Weil das bisher nicht so ist. " und "Why change running system?" ist kein guter Grund - 01 und 04 sind auch nicht die einzigen, die möglich sind.

**Comment by jplitza** [comment]
@genofire Weil der Prozess des Updatens der Zone und der DNS-Server fehlerhaft sein könnten und damit gleich den fürs Netz essentiellen Gateway ausschalten könnten. Ich würde da eher versuchen, Dienste die nicht unbedingt auf den Gateways laufen müssen auch nicht dort laufen zu lassen - und dazu zählt auch DNS. Im Gegenteil: Ich möchte eigentlich auch nodes.ffhb.de von dort wegziehen (da es dort im Moment eh nicht funktioniert). Und wir brauchen keine 6 DNS-Server, das macht höchstens mehr Ärger wenn dann einer nicht funktioniert und in 1/6 der Fälle irgendwas kaputt ist.

**Comment by genofire** [comment]
nodes.ffhb funktioniert (zumindest auf den neue Gates)

**Comment by ghost** [comment]
Und ns0[1-6].bremen.freifunk.net macht wieder Probleme mit UDP-Paket-Groesse...

**Comment by ghost** [comment]
Es funktioniert ja auch manchmal, nur halt nicht zuverlaessig immer

**Comment by ghost** [comment]
Was ich eine okaye Loesung finden wuerde, waere wenn Leute die Zone mithosten auf ihren DNS-Servern und wir somit SPOFs loswerden oder so...
