### ISSUE TITLE
DNS Zonentransfer

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ffhb-dns#9]
Irgendwie ist immer noch vpn05.ffhb.de unter der falsche IP-Adressen auf den Slave Servern vorhanden.

**Comment by genofire** [comment]
genofire  ~  dig @ns-1.moritzrudert.de +short vpn05.ffhb.de A
5.9.250.37
 genofire  ~  dig @ns-1.moritzrudert.de +short vpn05.ffhb.de AAAA
2a01:4f8:160:44d0:ffbc::2
 genofire  ~  dig @ns2.he.net +short vpn05.ffhb.de AAAA  
2a01:4f8:160:44d0:ffbc::2
 genofire  ~  dig @ns2.he.net +short vpn05.ffhb.de A  
5.9.250.37
 genofire  ~  dig @ns2.he.net +short vpn05.bremen.freifunk.net
5.9.250.37
 genofire  ~  dig @ns2.he.net +short vpn05.bremen.freifunk.net AAAA
2a01:4f8:160:44d0:ffbc::2
 genofire  ~  dig @dns.ffhb.de +short vpn05.bremen.freifunk.net AAAA
2a01:4f8:151:7104::244
 genofire  ~  dig @dns.ffhb.de +short vpn05.bremen.freifunk.net A  
176.9.190.244
 genofire  ~  dig @dns.ffhb.de +short vpn05.ffhb.de A  
176.9.190.244
 genofire  ~  dig @dns.ffhb.de +short vpn05.ffhb.de Aaaa
2a01:4f8:151:7104::244

**Comment by ghost** [comment]
Serial erhoehen loest das Problem -> closed
